name: "Continuous Integration"

on:
  - pull_request
  - push

jobs:
  continuous-integration-php81:
    name: "Continuous Integration php8.1"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
      - name: "Install Php 8.1"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          extensions: json, intl
      - name: "Validate composer.json"
        run: php $(which composer) validate --strict
      - name: "Install dependencies with composer"
        run: php $(which composer) install --no-interaction --no-progress --no-suggest
      - name: "Run PHP CodeSniffer"
        run: php vendor/bin/phpcs --standard=phpcs.xml
      - name: "Run PHP Unit Test"
        run: php vendor/bin/phpunit --configuration=phpunit.xml
  continuous-integration-php82:
    name: "Continuous Integration php8.2"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
      - name: "Install Php 8.2"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          #extensions: json, intl
      - name: "Validate composer.json"
        run: php $(which composer) validate --strict
      - name: "Install dependencies with composer"
        run: php $(which composer) install --no-interaction --no-progress --no-suggest
      - name: "Run PHP CodeSniffer"
        run: php vendor/bin/phpcs --standard=phpcs.xml
      - name: "Run PHP Unit Test"
        run: php vendor/bin/phpunit --configuration=phpunit.xml
  coding-standards-php83:
    name: "Continuous Integration php8.3"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
      - name: "Install Php 8.3"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          #extensions: json, intl
      - name: "Validate composer.json"
        run: php $(which composer) validate --strict
      - name: "Install dependencies with composer"
        run: php $(which composer) install --no-interaction --no-progress --no-suggest
      - name: "Run PHP CodeSniffer"
        run: php vendor/bin/phpcs --standard=phpcs.xml
      - name: "Run PHP Unit Test"
        run: php vendor/bin/phpunit --configuration=phpunit.xml
